### ISSUE TITLE
Malformed SpriggitSource record in top level RecordData.yaml?

### ISSUE THREAD

**Issue by rux616** [Mutagen-Modding/Spriggit#109]
Using Spriggit.Yaml.0.36.14, when I serialize a plugin, the `SpriggitSource` record in the top level ".\spriggit\\<plugin_name>.esm\RecordData.yaml" file appears to be malformed (compared to the previous version I was using).

Old version (Starfield.Yaml.0.34.0):

```yaml
SpriggitSource:
  PackageName: Spriggit.Yaml.Starfield
  Version: 0.34.0
```

New version (Starfield.Yaml.0.36.14):

```yaml
SpriggitSource:
  PackageName: 0.36.14
  Version: ''
```

CLI invocation: `serialize --InputPath .\data\<plugin_name>.esm --OutputPath .\spriggit\<plugin_name>.esm --GameRelease Starfield --PackageName Spriggit.Yaml --PackageVersion 0.36.14`
