### ISSUE TITLE
FormID List ANAM subrecord switched with LNAM[0] subrecord

### ISSUE THREAD

**Issue by rux616** [Mutagen-Modding/Spriggit#76]
Spriggit v0.25 mixes up the LNAM and ANAM subrecords if both are defined. (both "ShipVendorFramework.esm" and "Warhawk.esm" are light masters)

```yaml
FormKey: 000002:ShipVendorFramework.esm
EditorID: warhawk_ShipVendorDistribution_Location_NewAtlantis_Unique
FormVersion: 559
Items:
- 000001:ShipVendorFramework.esm
ANAM: 000822:Warhawk.esm
```

This is the output, but the contents of the ANAM entry and the content of the Items[0] entry should be reversed. (I'm trying to add `000822:Warhawk.esm` to `000001:ShipVendorFramework.esm`.)

Also, it seems like all the records have a FormKey of "XXXXXX:ShipVendorFramework.esm", when the plugin name is "Warhawk.esm". Might this be related to #75?
